# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :pumble_automation,
  ecto_repos: [PumbleAutomation.Repo],
  generators: [binary_id: true, timestamp_type: :utc_datetime_usec]

# Database and migration conventions. See docs/operations/migrations.md.
# UUID primary keys are generated by Ecto in the application, so no PostgreSQL
# extension is required. Timestamps are microsecond-precision UTC.
config :pumble_automation, PumbleAutomation.Repo,
  migration_lock: :pg_advisory_lock,
  migration_primary_key: [name: :id, type: :binary_id],
  migration_foreign_key: [column: :id, type: :binary_id],
  migration_timestamps: [type: :utc_datetime_usec]

# Starting queue concurrency and operational limits. Production overrides these
# from the environment in config/runtime.exs. Queue names are part of the durable
# job contract; the numbers are starting limits, not permanent scaling values.
queue_concurrency = [ingress: 20, executions: 20, schedules: 2, maintenance: 2]

config :pumble_automation,
  queue_concurrency: queue_concurrency,
  trusted_proxies: [],
  allowed_hosts: :any,
  limits: %{
    max_request_body_bytes: 1_048_576,
    outbound_http_timeout_ms: 10_000
  }

# The Pumble wire endpoints, and the scopes this application asks for.
#
# The Pumble client contract requires a fixed configured base URL: the host is never read
# from a token claim, a callback parameter, or any other value an outsider can
# influence. These are the official hosts from `docs/evidence/pumble_source_matrix.md`
# (source-matrix section 6, A-16 and A-17), and every environment inherits them unless it says
# otherwise. `config/dev.exs` and `config/test.exs` add the client identity to the
# same keyword list; production adds it from the environment in `config/runtime.exs`.
#
# `:bot_scopes` and `:user_scopes` are empty by default on purpose. The scope
# vocabulary is closed and known (sixteen strings, S-16), but the mapping from a
# product operation to a scope is still `PR-07` in the evidence register. Guessing
# a set here would ask a workspace to grant permissions this application cannot yet
# prove it needs, so a deployment configures the set it has decided on.
config :pumble_automation,
  pumble: [
    api_base_url: "https://api-ga.pumble.com",
    consent_url: "https://app.pumble.com/access-request",
    bot_scopes: [],
    user_scopes: []
  ]

# Bounded reading of Pumble callback bodies. Signature verification requires the exact
# request bytes to be retained before any JSON parsing, and the product limit sets the
# callback body limit at 1 MiB (`PR-12` is still open on the value Pumble itself
# enforces). The limit here is a byte count, not a rounded decimal one, because
# it is compared against bytes.
#
# `:path_prefix` is the only place raw bytes are retained. Every other route
# reads its body the ordinary way, so forms, JSON APIs, and LiveView uploads are
# unaffected by this setting.
#
# `:read_length` bounds one socket read and `:read_timeout` bounds how long that
# read may block, so a slow sender cannot hold a process open indefinitely.
#
# `:latency_warning_ms` is the internal handler budget. Pumble's deadline is
# three seconds (`K-7`), after which the user is told the app is unavailable, so
# the warning fires at less than half of it: a callback that is already this
# slow locally has no headroom left for the network.
config :pumble_automation, :pumble_callbacks,
  path_prefix: "/pumble/callbacks",
  max_body_bytes: 1_048_576,
  read_length: 65_536,
  read_timeout: 5_000,
  latency_warning_ms: 1_500

# Generic inbound webhooks. The path prefix is also the prefix
# `PumbleAutomationWeb.Plugs.CacheRawBody` retains bytes for, so the two
# must move together. The configured body cap is 512 KiB.
config :pumble_automation, :inbound_webhooks,
  path_prefix: "/hooks",
  max_body_bytes: 524_288,
  token_header: "x-webhook-token"

# Oban durable job execution. See ADR-0005 and docs/operations/oban.md.
#
# Plugins are deliberately minimal:
#   * Lifeline rescues jobs orphaned by an unclean node shutdown, which is
#     required for at-least-once execution across deployments.
#   * Pruner bounds unlimited growth of completed and discarded rows.
#   * Cron fires the system schedule dispatcher every minute, plus the four
#     maintenance ticks (reconcile, cleanup, integrity, retention). User clocks
#     live in `schedules`; they are not crontab entries.
config :pumble_automation, Oban,
  repo: PumbleAutomation.Repo,
  queues: queue_concurrency,
  shutdown_grace_period: :timer.seconds(30),
  plugins: [
    {Oban.Plugins.Lifeline, rescue_after: :timer.minutes(30)},
    {Oban.Plugins.Pruner, max_age: :timer.hours(24 * 7), limit: 10_000},
    {Oban.Plugins.Cron,
     crontab: [
       {"* * * * *", PumbleAutomation.Executions.Workers.ScheduleDispatcherWorker},
       {"*/5 * * * *", PumbleAutomation.Executions.Workers.ReconciliationWorker},
       {"17 * * * *", PumbleAutomation.Installations.CleanupWorker, args: %{kind: "cleanup"}},
       {"47 * * * *", PumbleAutomation.Installations.CleanupWorker, args: %{kind: "integrity"}},
       {"23 3 * * *", PumbleAutomation.Executions.Workers.RetentionWorker}
     ]}
  ]

# Configure the endpoint
config :pumble_automation, PumbleAutomationWeb.Endpoint,
  url: [host: "localhost"],
  adapter: Bandit.PhoenixAdapter,
  render_errors: [
    formats: [html: PumbleAutomationWeb.ErrorHTML, json: PumbleAutomationWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: PumbleAutomation.PubSub,
  live_view: [signing_salt: "dYnx/B0e"]

# Configure LiveView
config :phoenix_live_view,
  # the attribute set on all root tags. Used for Phoenix.LiveView.ColocatedCSS.
  root_tag_attribute: "phx-r"

# Configure esbuild (the version is required)
config :esbuild,
  version: "0.25.4",
  pumble_automation: [
    args:
      ~w(js/app.js --bundle --target=es2022 --outdir=../priv/static/assets/js --external:/fonts/* --external:/images/* --alias:@=.),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => [Path.expand("../deps", __DIR__), Mix.Project.build_path()]}
  ]

# Configure tailwind (the version is required)
config :tailwind,
  version: "4.3.0",
  pumble_automation: [
    args: ~w(
      --input=assets/css/app.css
      --output=priv/static/assets/css/app.css
    ),
    cd: Path.expand("..", __DIR__),
    env: %{"NODE_PATH" => [Path.expand("../deps", __DIR__), Mix.Project.build_path()]}
  ]

# Configure Elixir's Logger. Production replaces the formatter with JSON in
# config/prod.exs. These metadata keys are the structured log allowlist.
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [
    :request_id,
    :correlation_id,
    :provider_id,
    :installation_id,
    :workflow_id,
    :version_id,
    :execution_id,
    :step_id,
    :attempt_id,
    :job_id,
    :operation,
    :duration_ms,
    :status,
    :error_code,
    :error_class,
    :event_type,
    :content_bytes,
    :content_sha256
  ]

config :pumble_automation, PumbleAutomation.Logging,
  diagnostics_ttl_seconds: 900,
  diagnostics_max_ttl_seconds: 3_600

config :pumble_automation, PumbleAutomation.Diagnostics.Export,
  artifact_ttl_seconds: 900,
  max_artifact_ttl_seconds: 3_600,
  max_window_seconds: 604_800,
  max_executions: 20,
  max_bytes: 262_144

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# IANA timezone database for deterministic schedule calculation.
# Autoupdate is disabled so the same config, reference, and tzdata version
# always yield the same UTC instant. Packaged release is IANA 2026b.
config :elixir, :time_zone_database, Tzdata.TimeZoneDatabase
config :tzdata, :autoupdate, :disabled

# Parameters Phoenix must never write to a log line. `code` and `state` are the
# OAuth round trip: an authorization code in a debug log is a credential in a
# debug log, and it stays exchangeable until it is used. The rest are the usual
# credential names, listed so that a future endpoint cannot log one by accident.
config :phoenix, :filter_parameters, [
  "code",
  "state",
  "password",
  "token",
  "secret",
  "client-secret",
  "client_secret",
  "access_token",
  "refresh_token",
  "bot_token",
  "signing_secret",
  "authorization",
  "cookie",
  "x-webhook-token",
  "x-pumble-request-signature",
  "x-app-token"
]

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
