import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pumble_automation, PumbleAutomationWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  code_reloader: false,
  debug_errors: false

# Force using SSL in production. This also sets the Strict-Transport-Security
# header. Health probes stay on HTTP so an orchestrator hitting loopback is not
# redirected. `:force_ssl` is compile-time. `rewrite_on: [:x_forwarded_proto]`
# is required behind a TLS-terminating load balancer; `X-Forwarded-Host` is
# not rewritten, and `HostAllowlist` ignores it.
config :pumble_automation, PumbleAutomationWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    hsts: true,
    expires: 31_536_000,
    exclude: [
      paths: ["/health/live", "/health/ready"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# LiveDashboard and the code reloader are compile-time and must stay off.
config :pumble_automation, :dev_routes, false

# JSON one-object-per-line. Level is overridden from LOG_LEVEL in runtime.exs.
config :logger, :default_handler, formatter: {PumbleAutomation.Logging, %{}}
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
