defmodule PumbleAutomationWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pumble_automation

  alias PumbleAutomation.Limits

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # `secure` and `http_only` match the browser session cookie in
  # `PumbleAutomationWeb.BrowserSession`.
  @session_options [
    store: :cookie,
    key: "_pumble_automation_key",
    signing_salt: "4WXH5tn1",
    same_site: "Lax",
    http_only: true,
    secure: true
  ]

  # Plug.Parsers `length` is a backstop. Per-path caps live in
  # `PumbleAutomationWeb.Plugs.CacheRawBody` and follow `Limits`.
  @max_parser_bytes Limits.hard_cap(:max_request_body_bytes)

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :pumble_automation,
    gzip: not code_reloading?,
    only: PumbleAutomationWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :pumble_automation

    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug PumbleAutomationWeb.Plugs.TrustedProxies
  plug PumbleAutomationWeb.Plugs.HostAllowlist
  plug PumbleAutomationWeb.Plugs.SecurityHeaders

  # `:body_reader` is what makes signature verification possible. For a Pumble
  # callback path it retains the exact bytes in `conn.private[:raw_body]` and
  # enforces the Section 31 body limit before a decoder runs. Inbound webhook
  # paths are retained the same way at the 512 KiB cap. Every other path is
  # capped at `Limits.get(:max_request_body_bytes)` and is not retained. See
  # `PumbleAutomationWeb.Plugs.CacheRawBody`.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {PumbleAutomationWeb.Plugs.CacheRawBody, :read_body, []},
    json_decoder: Phoenix.json_library(),
    length: @max_parser_bytes,
    read_timeout: 5_000

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PumbleAutomationWeb.Router
end
